{
 "title": "batch-processing-dashboard2",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "timeRate",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Среднее время выполнения задач(jobs)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(spring_batch_job_seconds_sum{spring_batch_job_name=\"importProductJob\"}[1h])\n/\nrate(spring_batch_job_seconds_count{spring_batch_job_name=\"importProductJob\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество обработанных продуктов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "batch_products_processed_total{job=\"batch-processing\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Процент успешных выполнений ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(spring_batch_job_seconds_count{spring_batch_job_status=\"COMPLETED\"}[1d])) \n/ \nsum(increase(spring_batch_job_seconds_count[1d]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество выполненных задач по импорту продукта.",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "batch_job_result_total{status=\"COMPLETED\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}